feat : 요구사항 4 N+M+K 구현
lette1394/string-calculator pull request #7
Opened 2021-07-10 13:57 UTC by Gyoung-min

- 전체 변수명 수정

2021-07-10 16:08 UTC, lette1394 commented
@Gyoung-min 
conflict 해결해주세요ㅎㅎ

2021-07-10 16:10 UTC, lette1394 requested changes

2021-07-10 16:10 UTC, lette1394 commented on iter-1/src/main/java/com/github/lette1394/App.java
> +    final List<String> expression = new ArrayList<>(Arrays.asList(getOperator.split("\\+")));
`ArrayList`가 아니라, `List`로 `expression`을 받아서, interface를 사용한 점이 좋습니다 👍 
항상 interface를 먼저 사용할 수 없을까? 고민해주세요

2021-07-10 16:10 UTC, lette1394 commented on iter-1/src/main/java/com/github/lette1394/App.java
> +    if (expression.size() == 2) {
빈 줄 하나 넣어주면 좋을 거 같아요

```suggestion
    final long operand3 = Long.parseLong(expression.get(2));
    
    if (expression.size() == 2) {
```

2021-07-12 08:02 UTC, Gyoung-min commented on iter-1/src/main/java/com/github/lette1394/App.java
> +    final List<String> expression = new ArrayList<>(Arrays.asList(getOperator.split("\\+")));
ArrayList와 List에 대한 추가 학습을 진행했습니다
https://github.com/Gyoung-min/algorithm_prectice/issues/70

2021-07-12 09:16 UTC, lette1394 approved these changes
LGTM 👍👍👍
merge 합니다

2021-07-12 09:16 UTC, merged